name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-frontend:
    name: Build Frontend Docker Image 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4
        with:
          sparse-checkout: EduCloud

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry 🚢
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          build-args: |
            VITE_API_URL=https://api-educloud.pollak.info
          push: true
          tags: ghcr.io/pollak-projects/educloud/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

 triggerUpdate:
   name: Trigger Update 🔄
   runs-on: ubuntu-latest
   needs: [build-frontend]
   steps:
     - name: Call Webhook
       uses: distributhor/workflow-webhook@v3
       with:
         webhook_url: ${{ secrets.WEBHOOK_URL }}
